### ISSUE TITLE
Configure fails on linux

### ISSUE THREAD

**Issue by 4re** [HomeOfVapourSynthEvolution/VapourSynth-Bilateral#5]
You should not use -Werror on this kind of checks.
```
checking for vapoursynth headers...
#include <VapourSynth.h>
int main(void){getVapourSynthAPI; return 0;}
clang++ conftest.cpp -Werror -o conftest -Os -ffast-math -std=c++11 -Wall -I. -I./include -msse2 -fPIC -I/usr/include/vapoursynth
conftest.cpp:4:16: error: expression result unused [-Werror,-Wunused-value]
int main(void){getVapourSynthAPI; return 0;}
               ^~~~~~~~~~~~~~~~~
1 error generated
```
Also ```-fexcess-precision=fast``` is incompatible with clang, and it's on by default with gcc.
```
int main(void){ return 0;}
clang++ conftest.cpp -Werror -o conftest -Os -ffast-math -std=c++11 -Wall -I. -I./include -msse2 -fPIC -fexcess-precision=fast
x86_64-pc-linux-gnu-clang-3.6.1: error: optimization flag '-fexcess-precision=fast' is not supported
1
```
But I think it's a C only feature and not used anyways if ```-ffast-math``` is on.
https://gcc.gnu.org/onlinedocs/gcc-5.1.0/gcc/Optimize-Options.html

**Comment by 4re** [comment]
You should assign some value to the variable ```DEPLIBS```, like for example ```DEPLIBS="vapoursynth"``` to make the pkg-config check work.

**Comment by mawen1250** [comment]
Thanks for the report and PR, merged now.
